import os

DATA_DIR = "data"

TEAMS_JSON_FILE = "teams.json"
TEAMS_JSON_PATH = os.path.join(DATA_DIR, TEAMS_JSON_FILE)

# probabilities
P_HOME_ICE_WIN = 0.50
P_HOME_ICE_LOSS = 0.40
HOME_ICE_WEIGHT = 0.20
P_RANDOM_CHANCE_WIN = 0.42
P_RANDOM_CHANCE_LOSS = 0.42
RANDOM_CHANGE_WEIGHT = 0.1
P_RATING_DIFF_WIN = 0.42
P_RATING_DIFF_LOSS = 0.42
RATING_DIFF_WEIGHT = 0.70
RATING_DIFF_SCALE_FACTOR = 0.04
# max goals scorable in a game
MAX_GOALS = 7
# team ratings
MIN_RATING = 1
MAX_RATING = 7
# points
POINTS_PER_WIN = 2
POINTS_PER_TIE = 1
# number of games
HOME_DIVISIONAL_GAMES = 2
HOME_INTRACONF_SUBDIV_GAMES = 2
HOME_INTRACONF_GAMES = 1
HOME_INTERCONF_GAMES = 1
